-- migrations/postgresql/001_initial_schema.sql
-- Schema PostgreSQL do TechLab+ Aldeia / ACASA (ADR-003).
--
-- Esta migration reproduz o ESTADO LOGICO FINAL produzido pelas migrations
-- SQLite historicas 001 + 002 + 003, que permanecem intactas e nao editaveis:
--
--   migrations/001_initial_schema.sql              (schema inicial)
--   migrations/002_legacy_cell_valor_bruto_tipado.sql  (tipo/formula/JSON da celula)
--   migrations/003_comprovante_por_movimento.sql   (indices de comprovante)
--
-- Ela e uma migration NOVA de uma trilha NOVA, nao uma conversao textual das
-- tres. As colunas da 002 ja nascem na tabela e os indices da 003 ja nascem
-- criados: o historico de COMO o SQLite chegou ali e do SQLite, e replica-lo em
-- tres arquivos aqui nao acrescentaria nenhuma garantia.
--
-- Convencoes obrigatorias (baseline FROZEN, inalteradas pelo ADR-003):
--   T-06 : todo valor monetario e INTEIRO em CENTAVOS. Nunca REAL/FLOAT/NUMERIC
--          aproximado. Aqui: BIGINT (ver nota abaixo).
--   M-01 : este schema NAO espelha a planilha legada.
--   M-02 : movimento <-> competencia e N:N via `alocacao`.
--   M-05 : `movimento_financeiro.associado_id` e OPCIONAL (deposito nao identificado).
--   M-06 : status cadastral != situacao financeira (nao ha coluna de situacao financeira).
--   M-07 : proveniencia do legado em `legacy_cell` / `legacy_cell_link`.
--   M-09 : correcao por INATIVACAO (`ativo = false`), nunca por DELETE fisico.
--          Inativar SEMPRE exige `inativado_em` e `motivo_inativacao` nao vazio.
--   M-10 : competencia e DADO (linhas), nunca coluna mensal.
--
-- Nenhuma FK usa ON DELETE CASCADE em entidade financeira: preservacao historica.
--
-- ---------------------------------------------------------------------------
-- Decisoes de tipo, e por que cada uma preserva a semantica do SQLite
-- ---------------------------------------------------------------------------
--
-- IDENTIDADE — `INTEGER GENERATED BY DEFAULT AS IDENTITY` no lugar de
--   `INTEGER PRIMARY KEY AUTOINCREMENT`. E `BY DEFAULT`, e nao `ALWAYS`, de
--   proposito: a transferencia SQLite -> PostgreSQL (PG-2+) precisa INSERIR os
--   ids historicos explicitamente para nao quebrar as FKs ja existentes, e
--   `ALWAYS` recusaria isso sem `OVERRIDING SYSTEM VALUE`.
--   Consequencia a tratar na migracao de dados: apos inserir ids explicitos, a
--   sequence precisa ser ressincronizada (`setval`), senao o proximo INSERT
--   automatico colide com um id ja usado.
--
-- DINHEIRO — BIGINT, nao INTEGER. O `INTEGER` do SQLite ja e de 64 bits; usar
--   `int4` aqui ESTREITARIA o dominio de ~9,2e18 para ~2,1e9 centavos
--   (R$ 21 milhoes), o que seria uma mudanca de regra disfarcada de conversao de
--   tipo. `node-postgres` entrega `int8` como string; o parser validado em
--   `src/db/postgresql/connection.js` converte para Number apenas dentro de
--   `Number.MAX_SAFE_INTEGER` e LANCA fora dela.
--   REAL / FLOAT / DOUBLE PRECISION sao proibidos para valor oficial (T-06).
--
-- BOOLEANO — `ativo BOOLEAN` no lugar de `ativo INTEGER CHECK (ativo IN (0,1))`.
--   O CHECK do SQLite existia para simular um booleano que o SQLite nao tem;
--   `BOOLEAN` da a mesma garantia no nivel do tipo. A regra M-09 nao muda: o
--   CHECK de inativacao continua exigindo QUANDO e POR QUE.
--
-- TIMESTAMP — `TIMESTAMPTZ` no lugar de TEXT ISO-8601. O texto era a convencao
--   possivel no SQLite, nao uma regra do dominio. `now()` substitui
--   `strftime('%Y-%m-%dT%H:%M:%SZ','now')` com a mesma intencao (instante de
--   auditoria) e mais precisao.
--
-- DATA CIVIL — `movimento_financeiro.data`, `ajuste_credito_debito.data` e
--   `comprovante.data` viram `DATE`, e nao TIMESTAMPTZ: sao data civil do fato
--   financeiro (o dia do deposito), sem hora e sem fuso. Promove-las a instante
--   introduziria um deslocamento de fuso capaz de mover um pagamento de mes —
--   e portanto de competencia (M-10).

-- ---------------------------------------------------------------------------
-- associado
-- ---------------------------------------------------------------------------
CREATE TABLE associado (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- ID da planilha preservado como TEXTO (pode ter zeros a esquerda / nao numerico).
  legacy_id           TEXT UNIQUE,
  nome                TEXT NOT NULL,
  -- Status CADASTRAL. Nao e situacao financeira (M-06).
  status_cadastral    TEXT NOT NULL DEFAULT 'indefinido'
                        CHECK (status_cadastral IN ('ativo', 'inativo', 'desligado', 'indefinido')),
  -- Codigo bruto da planilha ('a', 'i', 'DESLIGADO', ...) preservado SEM interpretacao.
  -- TO CONFIRM: o significado oficial destes codigos ainda nao foi decidido.
  -- Nenhum mapeamento automatico legacy_status_code -> status_cadastral deve existir.
  legacy_status_code  TEXT,
  observacoes         TEXT,
  criado_em           TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_associado_nome ON associado (nome);
CREATE INDEX ix_associado_status ON associado (status_cadastral);

-- ---------------------------------------------------------------------------
-- competencia  (M-10: competencia e dado, nao coluna)
-- ---------------------------------------------------------------------------
CREATE TABLE competencia (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ano                      INTEGER NOT NULL CHECK (ano BETWEEN 1900 AND 2999),
  mes                      INTEGER NOT NULL CHECK (mes BETWEEN 1 AND 12),
  -- Valor esperado OPCIONAL. TO CONFIRM: mensalidade e vigencias nao estao decididas.
  valor_esperado_centavos  BIGINT
                             CHECK (valor_esperado_centavos IS NULL OR valor_esperado_centavos >= 0),
  -- Identificador livre de regra aplicavel (texto). Regra em si nao e implementada aqui.
  regra                    TEXT,
  observacao               TEXT,
  criado_em                TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em            TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (ano, mes)
);

-- ---------------------------------------------------------------------------
-- movimento_financeiro
-- ---------------------------------------------------------------------------
CREATE TABLE movimento_financeiro (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data                  DATE NOT NULL,
  -- T-06: centavos inteiros.
  valor_centavos        BIGINT NOT NULL CHECK (valor_centavos > 0),
  -- M-03: direcao do dinheiro e estruturada, nao texto livre.
  tipo                  TEXT NOT NULL CHECK (tipo IN ('credito', 'debito')),
  -- Origem do lancamento (deposito, transferencia, importacao...). Vocabulario ainda
  -- nao normativo, portanto texto livre com default explicito.
  origem                TEXT NOT NULL DEFAULT 'desconhecida',
  -- M-05: OPCIONAL. Deposito nao identificado existe sem associado.
  associado_id          INTEGER REFERENCES associado (id) ON DELETE RESTRICT,
  observacao            TEXT,
  estado_identificacao  TEXT NOT NULL DEFAULT 'nao_identificado'
                          CHECK (estado_identificacao IN ('identificado', 'nao_identificado', 'em_revisao')),
  -- M-09: correcao sem exclusao fisica.
  ativo                 BOOLEAN NOT NULL DEFAULT TRUE,
  inativado_em          TIMESTAMPTZ,
  motivo_inativacao     TEXT,
  criado_em             TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em         TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- M-09: inativar exige QUANDO e POR QUE. Sem os dois, o banco recusa.
  CONSTRAINT ck_movimento_inativacao_justificada CHECK (
    ativo
    OR (
      inativado_em IS NOT NULL
      AND motivo_inativacao IS NOT NULL
      AND trim(motivo_inativacao) <> ''
    )
  )
);

CREATE INDEX ix_movimento_data ON movimento_financeiro (data);
CREATE INDEX ix_movimento_associado ON movimento_financeiro (associado_id);
CREATE INDEX ix_movimento_identificacao ON movimento_financeiro (estado_identificacao);

-- ---------------------------------------------------------------------------
-- alocacao  (M-02: N:N entre movimento e competencia)
-- ---------------------------------------------------------------------------
CREATE TABLE alocacao (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movimento_id       INTEGER NOT NULL REFERENCES movimento_financeiro (id) ON DELETE RESTRICT,
  competencia_id     INTEGER NOT NULL REFERENCES competencia (id) ON DELETE RESTRICT,
  valor_centavos     BIGINT NOT NULL CHECK (valor_centavos > 0),
  observacao         TEXT,
  ativo              BOOLEAN NOT NULL DEFAULT TRUE,
  inativado_em       TIMESTAMPTZ,
  motivo_inativacao  TEXT,
  criado_em          TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em      TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- M-09: inativar exige QUANDO e POR QUE. Sem os dois, o banco recusa.
  CONSTRAINT ck_alocacao_inativacao_justificada CHECK (
    ativo
    OR (
      inativado_em IS NOT NULL
      AND motivo_inativacao IS NOT NULL
      AND trim(motivo_inativacao) <> ''
    )
  )
);

-- Um movimento so pode ter UMA alocacao ATIVA por competencia; alocacoes
-- inativadas permanecem no historico e nao bloqueiam uma nova (M-09).
CREATE UNIQUE INDEX ux_alocacao_ativa
  ON alocacao (movimento_id, competencia_id) WHERE ativo;

CREATE INDEX ix_alocacao_movimento ON alocacao (movimento_id);
CREATE INDEX ix_alocacao_competencia ON alocacao (competencia_id);

-- ---------------------------------------------------------------------------
-- ajuste_credito_debito  (M-03)
-- ---------------------------------------------------------------------------
CREATE TABLE ajuste_credito_debito (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  associado_id       INTEGER NOT NULL REFERENCES associado (id) ON DELETE RESTRICT,
  tipo               TEXT NOT NULL CHECK (tipo IN ('credito', 'debito')),
  valor_centavos     BIGINT NOT NULL CHECK (valor_centavos > 0),
  motivo             TEXT NOT NULL,
  data               DATE NOT NULL,
  competencia_id     INTEGER REFERENCES competencia (id) ON DELETE RESTRICT,
  observacao         TEXT,
  ativo              BOOLEAN NOT NULL DEFAULT TRUE,
  inativado_em       TIMESTAMPTZ,
  motivo_inativacao  TEXT,
  criado_em          TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em      TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- M-09: inativar exige QUANDO e POR QUE. Sem os dois, o banco recusa.
  CONSTRAINT ck_ajuste_inativacao_justificada CHECK (
    ativo
    OR (
      inativado_em IS NOT NULL
      AND motivo_inativacao IS NOT NULL
      AND trim(motivo_inativacao) <> ''
    )
  )
);

CREATE INDEX ix_ajuste_associado ON ajuste_credito_debito (associado_id);
CREATE INDEX ix_ajuste_competencia ON ajuste_credito_debito (competencia_id);

-- ---------------------------------------------------------------------------
-- comprovante  (M-04: conceito independente do pagamento)
-- ---------------------------------------------------------------------------
CREATE TABLE comprovante (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado              TEXT NOT NULL DEFAULT 'pendente'
                        CHECK (estado IN ('presente', 'ausente', 'pendente', 'nao_aplicavel')),
  -- Todos os vinculos sao OPCIONAIS: o comprovante existe por si so.
  movimento_id        INTEGER REFERENCES movimento_financeiro (id) ON DELETE RESTRICT,
  associado_id        INTEGER REFERENCES associado (id) ON DELETE RESTRICT,
  competencia_id      INTEGER REFERENCES competencia (id) ON DELETE RESTRICT,
  -- Referencia futura ao arquivo/evidencia. TO CONFIRM (C-06): armazenamento de
  -- arquivos nao foi decidido; NENHUM upload e implementado.
  referencia_externa  TEXT,
  data                DATE,
  observacao          TEXT,
  criado_em           TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_comprovante_movimento ON comprovante (movimento_id);
CREATE INDEX ix_comprovante_associado ON comprovante (associado_id);

-- Vindo da migration SQLite 003: um movimento tem, no maximo, UM comprovante.
-- Indice PARCIAL porque a restricao vale para comprovante VINCULADO a movimento;
-- comprovante independente (M-04) pode existir aos montes, sem movimento nenhum.
-- Em PostgreSQL varios NULL tambem nao colidem em UNIQUE, mas o `WHERE` mantem a
-- intencao escrita e o indice menor.
CREATE UNIQUE INDEX ux_comprovante_movimento
  ON comprovante (movimento_id) WHERE movimento_id IS NOT NULL;

-- Fila de pendencia de evidencia (F-05 / F-10): a consulta filtra por `estado`.
CREATE INDEX ix_comprovante_estado ON comprovante (estado);

-- ---------------------------------------------------------------------------
-- pendencia  (M-08: dado ambiguo preservado para revisao humana)
-- ---------------------------------------------------------------------------
CREATE TABLE pendencia (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo           TEXT NOT NULL,
  associado_id   INTEGER REFERENCES associado (id) ON DELETE RESTRICT,
  movimento_id   INTEGER REFERENCES movimento_financeiro (id) ON DELETE RESTRICT,
  descricao      TEXT NOT NULL,
  prioridade     TEXT NOT NULL DEFAULT 'media'
                   CHECK (prioridade IN ('baixa', 'media', 'alta')),
  estado         TEXT NOT NULL DEFAULT 'aberta'
                   CHECK (estado IN ('aberta', 'em_analise', 'resolvida', 'descartada')),
  resolucao      TEXT,
  resolvida_em   TIMESTAMPTZ,
  resolvida_por  TEXT,
  criado_em      TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_pendencia_fechada_tem_data CHECK (
    estado NOT IN ('resolvida', 'descartada') OR resolvida_em IS NOT NULL
  )
);

CREATE INDEX ix_pendencia_estado ON pendencia (estado);
CREATE INDEX ix_pendencia_associado ON pendencia (associado_id);

-- ---------------------------------------------------------------------------
-- importacao  (M-07)
-- ---------------------------------------------------------------------------
CREATE TABLE importacao (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_arquivo       TEXT NOT NULL,
  -- UNIQUE: impede reimportacao SILENCIOSA do mesmo arquivo. Reimportar exige
  -- acao explicita (inativar/registrar a importacao anterior).
  sha256             TEXT NOT NULL UNIQUE CHECK (length(sha256) = 64),
  importado_em       TIMESTAMPTZ NOT NULL DEFAULT now(),
  versao_importador  TEXT NOT NULL,
  status             TEXT NOT NULL DEFAULT 'pendente'
                       CHECK (status IN ('pendente', 'concluida', 'falhou', 'revertida')),
  -- Resumo serializado (JSON) do resultado da importacao.
  resultado          TEXT,
  observacao         TEXT
);

-- ---------------------------------------------------------------------------
-- legacy_cell  (M-07: proveniencia ate arquivo/aba/celula/valor bruto)
-- Inclui, ja na criacao, as colunas acrescentadas pela migration SQLite 002.
-- ---------------------------------------------------------------------------
CREATE TABLE legacy_cell (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  importacao_id   INTEGER NOT NULL REFERENCES importacao (id) ON DELETE RESTRICT,
  aba             TEXT NOT NULL,
  endereco        TEXT NOT NULL,
  linha           INTEGER,
  coluna          INTEGER,
  -- VALOR BRUTO ORIGINAL, sempre TEXTO. Nunca substituido por interpretacao.
  valor_bruto     TEXT,
  -- Estilo relevante da celula serializado (JSON): cor de fundo, negrito, etc.
  -- TO CONFIRM: cores nao documentadas nao possuem significado definido.
  estilo          TEXT,
  -- Classificacao atribuida posteriormente pelo importador/revisor.
  classificacao   TEXT,
  estado_revisao  TEXT NOT NULL DEFAULT 'nao_revisado'
                    CHECK (estado_revisao IN ('nao_revisado', 'revisado', 'ambiguo', 'descartado')),
  -- --- migration SQLite 002 (proveniencia sem coercao destrutiva) ---
  -- Tipo declarado pela biblioteca de leitura. SEM CHECK, de proposito: o
  -- vocabulario acompanha a biblioteca e nao e regra de negocio FROZEN; um tipo
  -- novo deve CHEGAR ao banco em vez de virar erro.
  tipo_original   TEXT,
  -- Expressao da formula legada. F-07: formula legada NUNCA e saldo oficial;
  -- fica aqui apenas como evidencia.
  formula         TEXT,
  -- Representacao formatada exibida pela planilha (formatacao e do arquivo, nao do dado).
  texto_formatado TEXT,
  -- Payload bruto estruturado (JSON) da celula: o registro NAO-ambiguo, que
  -- distingue numero, texto, data, booleano, formula, erro e vazio sem heuristica.
  valor_json      TEXT,
  criado_em       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (importacao_id, aba, endereco)
);

CREATE INDEX ix_legacy_cell_importacao ON legacy_cell (importacao_id);
CREATE INDEX ix_legacy_cell_revisao ON legacy_cell (estado_revisao);

-- Vinculo explicito celula -> entidade produzida por ela.
-- Referencia polimorfica intencional (sem FK): aponta para varias tabelas.
CREATE TABLE legacy_cell_link (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_cell_id  INTEGER NOT NULL REFERENCES legacy_cell (id) ON DELETE RESTRICT,
  entidade_tipo   TEXT NOT NULL
                    CHECK (entidade_tipo IN ('associado', 'competencia', 'movimento_financeiro',
                                             'alocacao', 'ajuste_credito_debito', 'comprovante',
                                             'pendencia')),
  entidade_id     INTEGER NOT NULL,
  papel           TEXT NOT NULL DEFAULT 'origem',
  criado_em       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (legacy_cell_id, entidade_tipo, entidade_id, papel)
);

CREATE INDEX ix_legacy_cell_link_entidade ON legacy_cell_link (entidade_tipo, entidade_id);

-- ---------------------------------------------------------------------------
-- audit_log
-- Estrutura preparada. O preenchimento automatico e responsabilidade da
-- aplicacao (nao ha trigger nesta fase).
-- ---------------------------------------------------------------------------
CREATE TABLE audit_log (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ator              TEXT NOT NULL DEFAULT 'sistema',
  acao              TEXT NOT NULL,
  entidade_tipo     TEXT NOT NULL,
  entidade_id       TEXT,
  estado_anterior   TEXT,
  estado_posterior  TEXT,
  metadados         TEXT,
  criado_em         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_audit_entidade ON audit_log (entidade_tipo, entidade_id);
CREATE INDEX ix_audit_criado_em ON audit_log (criado_em);
