'use strict';

/**
 * Fatos de TIPO do PostgreSQL (ADR-003).
 *
 * Este modulo reune o que a camada de persistencia precisa saber sobre os tipos
 * do banco: o teto do `int4` das chaves e o parser da data civil. Sao decisoes
 * que valem para TODA a trilha PostgreSQL, entao ficam em um lugar so — duas
 * copias de um limite numerico ou de um formato de data e o comeco de uma
 * divergencia silenciosa entre consumidores.
 *
 * Nada aqui abre conexao, emite SQL ou conhece `src/services/`.
 */

// ---------------------------------------------------------------------------
// Chaves primarias — `int4`
// ---------------------------------------------------------------------------
//
// `associado.id`, `movimento_financeiro.id` e `comprovante.id` sao
// `INTEGER GENERATED BY DEFAULT AS IDENTITY`, ou seja `int4`. O SQLite, por
// contraste, usa `INTEGER PRIMARY KEY` de 64 bits.
//
// Isso cria uma armadilha de EQUIVALENCIA: a validacao de entrada aceita
// qualquer inteiro seguro do JavaScript (ate 2^53-1), porque essa e uma regra de
// dominio e nao do banco. Um id valido pela regra, porem acima do teto do int4,
// nao pode existir na coluna — e mandar esse valor ao PostgreSQL faz o servidor
// recusar com `22003 value out of range for type integer`, enquanto o SQLite
// simplesmente nao acha a linha.
//
// O contrato observavel tem de ser o mesmo nos dois: id que NAO PODE existir e
// indistinguivel de id que nao existe. Por isso a persistencia PostgreSQL filtra
// esses ids ANTES da consulta, em vez de deixar o erro do driver vazar como se
// fosse falha de infraestrutura.
const ID_MAXIMO_INT4 = 2_147_483_647;

/**
 * O id cabe na coluna `int4`?
 *
 * `false` significa "esta linha nao pode existir", que a persistencia traduz em
 * ausencia de linha — nunca em erro.
 *
 * @param {unknown} id
 * @returns {boolean}
 */
function cabeNoInt4(id) {
  return Number.isInteger(id) && id >= -ID_MAXIMO_INT4 - 1 && id <= ID_MAXIMO_INT4;
}

// ---------------------------------------------------------------------------
// DATA CIVIL — `DATE` nunca vira instante (M-10)
// ---------------------------------------------------------------------------
//
// `movimento_financeiro.data`, `ajuste_credito_debito.data` e `comprovante.data`
// sao DATE: data civil do fato financeiro, sem hora e sem fuso.
//
// O parser PADRAO do `node-postgres` converte `DATE` em um `Date` do JavaScript
// na MEIA-NOITE LOCAL do processo. Isso reintroduz exatamente o fuso que a
// escolha do tipo eliminou, e o estrago e silencioso: em uma maquina a leste de
// Greenwich, '2026-01-10' vira `2026-01-09T21:00:00Z`, e qualquer serializacao
// em UTC devolve o DIA ANTERIOR. Um pagamento pode mudar de dia, de mes e
// portanto de COMPETENCIA (M-10) por causa de onde o servidor esta.
//
// Devolver o texto como veio nao envolve fuso nenhum, e e o mesmo formato que o
// SQLite ja guarda. Mas devolver QUALQUER texto seria ingenuo: o PostgreSQL
// tambem emite valores de `DATE` que NAO sao datas civis de quatro digitos —
// verificados no servidor, nao supostos:
//
//     'infinity'        -> data infinita
//     '-infinity'       -> data infinita negativa
//     '0044-03-15 BC'   -> era anterior a Cristo, com sufixo
//     '12026-01-10'     -> ano de cinco digitos
//
// Nenhum deles e representavel no contrato 'YYYY-MM-DD' que o resto do sistema
// assume, e deixa-los passar os faria circular como se fossem datas comuns ate
// alguem compara-los ou formata-los. A recusa e RUIDOSA, pela mesma razao que o
// parser de `int8` lanca fora da faixa segura (T-06): melhor explodir na
// fronteira do que carregar um valor que ninguem sabe interpretar.
const PG_TYPE_DATE = 1082;

/** Data civil de quatro digitos. O PostgreSQL ja garante a validade do calendario. */
const DATA_CIVIL_RE = /^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/;

/**
 * Parser de `DATE`: devolve o texto 'YYYY-MM-DD' do PostgreSQL, sem fuso.
 *
 * @param {string | null} value
 * @returns {string | null}
 * @throws {RangeError} para valores de DATE que nao sao data civil de 4 digitos.
 */
function parseDataCivilSegura(value) {
  if (value === null || value === undefined) return null;

  if (typeof value !== 'string' || !DATA_CIVIL_RE.test(value)) {
    throw new RangeError(
      `Valor de DATE fora do contrato de data civil 'YYYY-MM-DD': ${JSON.stringify(value)}. ` +
        'Converter isto em data aqui produziria um dia sem significado (M-10).'
    );
  }
  return value;
}

module.exports = {
  ID_MAXIMO_INT4,
  cabeNoInt4,
  PG_TYPE_DATE,
  DATA_CIVIL_RE,
  parseDataCivilSegura,
};
